
DEBUG = True
SECRET_KEY = 'super-secret-key'

SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:123@localhost/app'
SQLALCHEMY_TRACK_MODIFICATIONS = False

#MAIL_DEFAULT_SENDER = 'your@mail.com'
#MAIL_SERVER = 'smtp.postmarkapp.com'
#MAIL_PORT = 25
#MAIL_USE_TLS = True
#MAIL_USERNAME = 'username'
#MAIL_PASSWORD = 'password'

SECURITY_CONFIRM_WITHIN = '5 days'
SECURITY_PASSWORD_HASH = 'plaintext'
SECURITY_PASSWORD_SALT = 'password_salt'
SECURITY_POST_LOGIN_VIEW = '/'
SECURITY_REGISTERABLE = True
SECURITY_REMEMBER_SALT = 'remember_salt'
SECURITY_RESET_SALT = 'reset_salt'
SECURITY_RESET_WITHIN = '5 days'
SECURITY_SEND_REGISTER_EMAIL = False
